# Generated by Django 4.0 on 2023-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GID', models.CharField(max_length=50, verbose_name='比賽編號')),
                ('GName', models.CharField(max_length=50, verbose_name='比賽名稱')),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False, verbose_name='球員編號')),
                ('GID', models.CharField(max_length=20, verbose_name='比賽編號')),
                ('PName', models.CharField(max_length=20, verbose_name='會員姓名')),
                ('NUM', models.IntegerField(null=True, verbose_name='球衣號')),
                ('MIN', models.IntegerField(null=True, verbose_name='上場時間')),
                ('PTS', models.IntegerField(null=True, verbose_name='分數')),
                ('REB', models.IntegerField(null=True, verbose_name='籃板')),
                ('OR', models.IntegerField(null=True, verbose_name='攻籃')),
                ('BR', models.IntegerField(null=True, verbose_name='守籃')),
                ('AST', models.IntegerField(null=True, verbose_name='助攻')),
                ('STL', models.IntegerField(null=True, verbose_name='抄截')),
                ('BLK', models.IntegerField(null=True, verbose_name='阻攻')),
                ('TO', models.IntegerField(null=True, verbose_name='失誤')),
                ('FG', models.IntegerField(null=True, verbose_name='2分球')),
                ('TP', models.IntegerField(null=True, verbose_name='3分球')),
                ('FT', models.IntegerField(null=True, verbose_name='罰球')),
                ('GS', models.CharField(choices=[('GS', '首發'), ('BENCH', '替補'), ('DNP', '未上場')], default='DNP', max_length=5, verbose_name='狀態')),
            ],
        ),
    ]
