# Generated by Django 4.0 on 2023-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0002_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='FG',
            field=models.CharField(max_length=10, null=True, verbose_name='2分球'),
        ),
    ]
