# Generated by Django 4.0 on 2023-07-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0003_alter_players_fg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='FT',
            field=models.CharField(max_length=10, null=True, verbose_name='罰球'),
        ),
        migrations.AlterField(
            model_name='players',
            name='TP',
            field=models.CharField(max_length=10, null=True, verbose_name='3分球'),
        ),
    ]
