# Generated by Django 4.0 on 2023-07-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0005_defensivestats_intelligence_p_intelligence_t_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defensivestats',
            old_name='OSID',
            new_name='DSID',
        ),
    ]
